using inercya.EntityLite.Builders;
using System;
using System.Collections.Generic;
using System.Data.Common;
using System.Linq;
using System.Text;

namespace inercya.EntityLite.Providers
{
    public interface IEntityLiteProvider
    {
        string ParameterPrefix { get; }
        string StartQuote { get; }
        string EndQuote { get; }
        string DefaultSchema { get; set; }

        AutoGeneratedFieldFetchMode AutoGeneratedFieldFetchMode { get; }

        string SequenceVariable { get; }

        string Concat(params string[] strs);

        string GetPagedQuery(AbstractQueryBuilder builder, DbCommand selectCommand, ref int paramIndex, int fromRowIndex, int toRowIndex);

        DbCommand GenerateInsertCommand(CommandBuilder commandBuilder, object entity);

    }
}
